version: "3"

services:
    # ------------------------------------#
    #             Redis Server            #
    # ------------------------------------#
    redisMaster:
        image: redis:latest
        container_name: "redisMaster"
        volumes:
            - "./config/master.conf:/usr/local/etc/redis/redis.conf"
            - "./logs/redis/redis1.log:/var/log/redis/redis.log"
        # restart: always
        ports:
            - "6379:6379"
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
        networks:
            - sentinel
    # -----------------
    redisSlave:
        image: redis:latest
        container_name: "redisSlave"
        volumes:
            - "./config/slave.conf:/usr/local/etc/redis/redis.conf"
            - "./logs/redis/redis2.log:/var/log/redis/redis.log"
        # restart: always
        ports:
            - "6380:6379"
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
        networks:
            - sentinel
        depends_on:
            - redisMaster
    # -----------------
    redisSlave2:
        image: redis:latest
        container_name: "redisSlave2"
        volumes:
            - "./config/slave2.conf:/usr/local/etc/redis/redis.conf"
            - "./logs/redis/redis3.log:/var/log/redis/redis.log"
        # restart: always
        ports:
            - "6381:6379"
        expose:
            - "6379"
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
        networks:
            - sentinel
        depends_on:
            - redisMaster
    # ------------------------------------#
    #           Redis Sentinel            #
    # ------------------------------------#
    redisSentinel:
        image: redis:latest
        container_name: "redisSentinel"
        volumes:
            - "./config/sentinel.conf:/usr/local/etc/redis/sentinel.conf"
            - "./logs/sentinel/sentinel1.log:/var/log/redis/sentinel.log"
        # restart: always
        ports:
            - "26379:26379"
        command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf"]
        networks:
            - sentinel
        depends_on:
            - redisMaster
    # -----------------
    redisSentinel2:
        image: redis:latest
        container_name: "redisSentinel2"
        volumes:
            - "./config/sentinel2.conf:/usr/local/etc/redis/sentinel.conf"
            - "./logs/sentinel/sentinel2.log:/var/log/redis/sentinel.log"
        ports:
            - "26380:26379"
        # restart: always
        command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf"]
        networks:
            - sentinel
        depends_on:
            - redisMaster
    # -----------------
    redisSentinel3:
        image: redis:latest
        container_name: "redisSentinel3"
        volumes:
            - "./config/sentinel3.conf:/usr/local/etc/redis/sentinel.conf"
            - "./logs/sentinel/sentinel3.log:/var/log/redis/sentinel.log"
        ports:
            - "26381:26379"
        # restart: always
        command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf"]
        networks:
            - sentinel
        depends_on:
            - redisMaster
networks:
    sentinel:
