version: "3"

services:
    # ------------------------------------#
    #             Redis Server            #
    # ------------------------------------#
    redis1:
        image: redis:latest
        container_name: "redis1"
        volumes:
            - "./config/redis1.conf:/usr/local/etc/redis/redis.conf"
            - "./logs/redis:/var/log/redis"
        # restart: always
        ports: 
            - 6379:6379
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
        network_mode: "host"
    # -----------------
    redis2:
        image: redis:latest
        container_name: "redis2"
        volumes:
            - "./config/redis2.conf:/usr/local/etc/redis/redis.conf"
            - "./logs/redis:/var/log/redis"
        # restart: always
        ports: 
            - 6380:6380
        command: ["redis-server", "/usr/local/etc/redis/redis.conf","--slaveof", "192.168.3.3", "6379"]
        network_mode: "host"
        depends_on:
            - redis1
    # -----------------
    redis3:
        image: redis:latest
        container_name: "redis3"
        volumes:
            - "./config/redis3.conf:/usr/local/etc/redis/redis.conf"
            - "./logs/redis:/var/log/redis"
        # restart: always
        ports: 
            - 6381:6381
        command: ["redis-server", "/usr/local/etc/redis/redis.conf","--slaveof", "192.168.3.3", "6379"]
        network_mode: "host"
        depends_on:
            - redis1
    # ------------------------------------#
    #           Redis Sentinel            #
    # ------------------------------------#
    redisSentinel:
        image: redis:latest
        container_name: "redisSentinel"
        volumes:
            - "./config/sentinel1.conf:/usr/local/etc/redis/sentinel.conf"
            - "./logs/sentinel:/var/log/redis"
        # restart: always
        ports: 
            - 26379:26379
        command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf"]
        network_mode: "host"
        depends_on:
            - redis1
    # -----------------
    redisSentinel2:
        image: redis:latest
        container_name: "redisSentinel2"
        volumes:
            - "./config/sentinel2.conf:/usr/local/etc/redis/sentinel.conf"
            - "./logs/sentinel:/var/log/redis"
        # restart: always
        ports: 
            - 26380:26380
        command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf"]
        network_mode: "host"
        depends_on:
            - redis1
    # -----------------
    redisSentinel3:
        image: redis:latest
        container_name: "redisSentinel3"
        volumes:
            - "./config/sentinel3.conf:/usr/local/etc/redis/sentinel.conf"
            - "./logs/sentinel:/var/log/redis"
        # restart: always
        ports: 
            - 26381:26381
        command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf"]
        network_mode: "host"
        depends_on:
            - redis1
